# Kubernetes compute node default networking template
#
parameters:
  linux:
    network:
      interface:
        ens2: ${_param:linux_dhcp_interface}
        ens3: ${_param:linux_single_interface}
#          mtu: 9000
#          enabled: true
#          type: slave
#          proto: manual
#          name: ${_param:primary_first_nic}
#          master: bond0
        ens4:
          enabled: true
          type: eth
          proto: static
          address: ${_param:tenant_address}
          netmask: ${_param:tenant_network_netmask}
          name_servers:
            - ${_param:dns_server01}
            - ${_param:dns_server02}

#          mtu: 9000
#          enabled: true
#          type: slave
#          proto: manual
#          name: ${_param:primary_second_nic}
#          master: bond0
#        bond0:
#          mtu: 9000
#          enabled: true
#          proto: manual
#          type: bond
#          use_interfaces:
#          - ${_param:primary_first_nic}
#          slaves: ${_param:primary_first_nic}
#          mode: active-backup
#        bond0.1:
#          mtu: 9000
#          name: bond0.${_param:control_vlan}
#          enabled: true
#          proto: static
#          type: vlan
#          use_interfaces:
#          - bond0
#          address: ${_param:single_address}
#          netmask: ${_param:control_network_netmask}
#        bond0.2:
#          mtu: 9000
#          name: bond0.${_param:tenant_vlan}
#          enabled: true
#          proto: static
#          type: vlan
#          use_interfaces:
#          - bond0
#          address: ${_param:tenant_address}
#          netmask: ${_param:tenant_network_netmask}
