
parameters:
  _param:
    salt_minion_ca_host: ${_param:infra_config_hostname}.${_param:cluster_domain}
    salt_minion_ca_authority: salt_master_ca

    # kubernetes settings
    kubernetes_admin_user: admin
    kubernetes_admin_password: LO76jBSN5INxhMMa
    kubernetes_admin_token: FuNWVKCJzr69TQgrZvjC5NplnN6X74r8
    kubernetes_kubelet_token: KWtKLBv4T2nRiJuXIA5vNwK50afRT3rU
    kubernetes_kube-proxy_token: WenjYkg82NIb8KDuOf2BYpCNzkcagBuP
    kubernetes_scheduler_token: vGZA6g6NvAsTOblzkyZjm1bVztfdC99A
    kubernetes_controller-manager_token: oXPxcebsaSuEtl5ipyUDuUrBI8enc3K6
    kubernetes_dns_token: wK4hUrN9rKT5JImUmsvL4z6jmbjaHvl0
    etcd_initial_token: g4S0a1SkEpXJpQhjyAHFok1Ak9unNNbP

    # addresses and hostnames
    kubernetes_internal_api_address: 10.254.0.1
    kubernetes_control_hostname: ctl
    kubernetes_control_address: 10.101.0.10
    kubernetes_control_node01_hostname: ctl01
    kubernetes_control_node02_hostname: ctl02
    kubernetes_control_node03_hostname: ctl03
    kubernetes_control_node01_address: 10.101.0.11
    kubernetes_control_node02_address: 10.101.0.12
    kubernetes_control_node03_address: 10.101.0.13

    cluster_vip_address: ${_param:kubernetes_control_address}
    cluster_local_address: ${_param:single_address}

    # etcd stuff
    cluster_node01_hostname: ${_param:kubernetes_control_node01_hostname}
    cluster_node01_address: ${_param:kubernetes_control_node01_address}
    cluster_node01_port: 4001
    cluster_node02_hostname: ${_param:kubernetes_control_node02_hostname}
    cluster_node02_address: ${_param:kubernetes_control_node02_address}
    cluster_node02_port: 4001
    cluster_node03_hostname: ${_param:kubernetes_control_node03_hostname}
    cluster_node03_address: ${_param:kubernetes_control_node03_address}
    cluster_node03_port: 4001

    kubernetes_virtlet_enabled: False
    openstack_control_address: None
    keystone_admin_password: None
    openstack_version: None
    keystone_service_token: None
    openstack_region: None
    kubernetes_control_node01_tenant_address: 10.102.0.11
    kubernetes_control_node02_tenant_address: 10.102.0.12
    kubernetes_control_node03_tenant_address: 10.102.0.13

  linux:
    network:
      host:
        ctl:
          address: ${_param:kubernetes_control_address}
          names:
          - ${_param:kubernetes_control_hostname}
          - ${_param:kubernetes_control_hostname}.${_param:cluster_domain}
        ctl01:
          address: ${_param:kubernetes_control_node01_address}
          names:
          - ${_param:kubernetes_control_node01_hostname}
          - ${_param:kubernetes_control_node01_hostname}.${_param:cluster_domain}
        ctl02:
          address: ${_param:kubernetes_control_node02_address}
          names:
          - ${_param:kubernetes_control_node02_hostname}
          - ${_param:kubernetes_control_node02_hostname}.${_param:cluster_domain}
        ctl03:
          address: ${_param:kubernetes_control_node03_address}
          names:
          - ${_param:kubernetes_control_node03_hostname}
          - ${_param:kubernetes_control_node03_hostname}.${_param:cluster_domain}
