parameters:
  salt:
    control:
      size:
        ceph.osd:
          cpu: 8
          ram: 16384
          disk_profile: large
          net_profile: cephnet
      cluster:
        internal:
          domain: ${_param:cluster_domain}
          engine: virt
          node:
            osd001:
              name: ${_param:ceph_osd_node01_hostname}
              provider: ${_param:infra_kvm_node04_hostname}.${_param:cluster_domain}
              image: ${_param:salt_control_xenial_image}
              size: ceph.osd
            osd002:
              name: ${_param:ceph_osd_node02_hostname}
              provider: ${_param:infra_kvm_node04_hostname}.${_param:cluster_domain}
              image: ${_param:salt_control_xenial_image}
              size: ceph.osd
            osd003:
              name: ${_param:ceph_osd_node03_hostname}
              provider: ${_param:infra_kvm_node04_hostname}.${_param:cluster_domain}
              image: ${_param:salt_control_xenial_image}
              size: ceph.osd

