parameters:
  salt:
    control:
      size:
        cmp.node:
          cpu: 8
          ram: 16384
          disk_profile: large
          net_profile: private
      cluster:
        internal:
          domain: ${_param:cluster_domain}
          engine: virt
          node:
            cmp001:
              name: ${_param:cmp_node01_hostname}
              provider: ${_param:infra_kvm_node04_hostname}.${_param:cluster_domain}
              image: ${_param:salt_control_xenial_image}
              size: cmp.node
            cmp002:
              name: ${_param:cmp_node02_hostname}
              provider: ${_param:infra_kvm_node04_hostname}.${_param:cluster_domain}
              image: ${_param:salt_control_xenial_image}
              size: cmp.node

