parameters:
  salt:
    control:
      size:
        openstack.gateway:
          cpu: 8
          ram: 8124
          disk_profile: small
          net_profile: private
      cluster:
        internal:
          domain: ${_param:cluster_domain}
          engine: virt
          node:
            gtw01:
              name: ${_param:openstack_gateway_node01_hostname}
              provider: ${_param:infra_kvm_node04_hostname}.${_param:cluster_domain}
              image: ${_param:salt_control_xenial_image}
              size: openstack.gateway

