parameters:
  salt:
    control:
      size:
        kubernetes.control:
          cpu: 8
          ram: 16384
          disk_profile: small
          net_profile: default
        kubernetes.compute:
          cpu: 8
          ram: 16384
          disk_profile: large
          net_profile: default
      cluster:
        internal:
          domain: ${_param:cluster_domain}
          engine: virt
          node:
            k8sctl01:
              name: ${_param:kubernetes_control_node01_hostname}
              provider: ${_param:infra_kvm_node04_hostname}.${_param:cluster_domain}
              image: ${_param:salt_control_xenial_image}
              size: kubernetes.control
            k8sctl02:
              name: ${_param:kubernetes_control_node02_hostname}
              provider: ${_param:infra_kvm_node04_hostname}.${_param:cluster_domain}
              image: ${_param:salt_control_xenial_image}
              size: kubernetes.control
            k8sctl03:
              name: ${_param:kubernetes_control_node03_hostname}
              provider: ${_param:infra_kvm_node04_hostname}.${_param:cluster_domain}
              image: ${_param:salt_control_xenial_image}
              size: kubernetes.control
            k8scmp01:
              name: ${_param:kubernetes_compute_node01_hostname}
              provider: ${_param:infra_kvm_node04_hostname}.${_param:cluster_domain}
              image: ${_param:salt_control_xenial_image}
              size: kubernetes.compute
            k8scmp02:
              name: ${_param:kubernetes_compute_node02_hostname}
              provider: ${_param:infra_kvm_node04_hostname}.${_param:cluster_domain}
              image: ${_param:salt_control_xenial_image}
              size: kubernetes.compute
            k8scmp03:
              name: ${_param:kubernetes_compute_node03_hostname}
              provider: ${_param:infra_kvm_node04_hostname}.${_param:cluster_domain}
              image: ${_param:salt_control_xenial_image}
              size: kubernetes.compute
